name = "Nouvelle Terre"
author = "0Sacha"
version = "1.0.83"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2319611dd179382553df8e3ee2dfd50d1353c25a0ec7f0d4f9ff7afce4dc7877"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
