name = "Nouvelle Terre"
author = "0Sacha"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e1ab4ff2aa18da473963762955d52106f12553caceb17dc12e0cad7e36003d2"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
