name = "Nouvelle Terre"
author = "0Sacha"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60034d3dd02980417327a02d91e9df0aa37a6ef14876fd200a76914995470e90"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
